package cache

import "testing"

// TestMixedAPI_NewToOld tests reading with old API what was written with new API.
func TestMixedAPI_NewToOld(t *testing.T) {
	tmpDir := t.TempDir()
	c := NewCacheWithStrategy(tmpDir, &DefaultCacheKeyStrategy{})

	ctx := NewKeyContext("plan-v2").Build()

	// Write with new API
	if err := c.MarkDoneWithContext(CacheGeometry, ctx); err != nil {
		t.Fatal(err)
	}

	// Read with old API
	// The key generated by the strategy should match the plan hash
	key := c.Strategy().ComputeKey(CacheGeometry, ctx)
	exists, err := c.ExistsLayer(CacheGeometry, key)
	if err != nil {
		t.Fatal(err)
	}
	if !exists {
		t.Error("old API should find cache written by new API")
	}
}

// TestMixedAPI_LayerIsolation tests that layer isolation works across APIs.
func TestMixedAPI_LayerIsolation(t *testing.T) {
	tmpDir := t.TempDir()
	c := NewCacheWithStrategy(tmpDir, &DefaultCacheKeyStrategy{})

	planHash := "layer-test"
	ctx := NewKeyContext(planHash).Build()

	// Write geometry with old API
	if err := c.MarkDoneLayer(CacheGeometry, planHash); err != nil {
		t.Fatal(err)
	}

	// Write artifact with new API
	if err := c.MarkDoneWithContext(CacheArtifact, ctx); err != nil {
		t.Fatal(err)
	}

	// Both should exist
	geoExists, _ := c.ExistsLayer(CacheGeometry, planHash)
	artExists, _ := c.ExistsWithContext(CacheArtifact, ctx)

	if !geoExists {
		t.Error("geometry should exist (written by old API)")
	}
	if !artExists {
		t.Error("artifact should exist (written by new API)")
	}

	// Metadata should not exist
	metaExists, _ := c.ExistsWithContext(CacheMetadata, ctx)
	if metaExists {
		t.Error("metadata should not exist")
	}
}

// TestMixedAPI_StrategyChange tests behavior when strategy changes mid-use.
func TestMixedAPI_StrategyChange(t *testing.T) {
	tmpDir := t.TempDir()
	c := NewCacheWithStrategy(tmpDir, &DefaultCacheKeyStrategy{})

	ctx := NewKeyContext("strategy-change").Build()

	// Write with default strategy
	if err := c.MarkDoneWithContext(CacheGeometry, ctx); err != nil {
		t.Fatal(err)
	}

	// Verify it exists
	exists, _ := c.ExistsWithContext(CacheGeometry, ctx)
	if !exists {
		t.Fatal("cache entry should exist before strategy change")
	}

	// Change strategy (simulating a different key generation)
	newStrategy := &DefaultCacheKeyStrategy{}
	c.SetStrategy(newStrategy)

	// Should still find the entry (same key generation logic)
	exists, _ = c.ExistsWithContext(CacheGeometry, ctx)
	if !exists {
		t.Error("cache entry should still exist after strategy change (same algorithm)")
	}
}

// TestMixedAPI_DifferentContexts tests that different contexts produce correct keys.
func TestMixedAPI_DifferentContexts(t *testing.T) {
	tmpDir := t.TempDir()
	c := NewCacheWithStrategy(tmpDir, &DefaultCacheKeyStrategy{})

	// Different contexts with same plan hash
	ctx1 := NewKeyContext("same-hash").
		WithProductID("product-a").
		Build()

	ctx2 := NewKeyContext("same-hash").
		WithProductID("product-b").
		Build()

	// Write with ctx1
	if err := c.MarkDoneWithContext(CacheGeometry, ctx1); err != nil {
		t.Fatal(err)
	}

	// In Phase 5, both contexts produce the same key (only plan hash matters)
	exists1, _ := c.ExistsWithContext(CacheGeometry, ctx1)
	exists2, _ := c.ExistsWithContext(CacheGeometry, ctx2)

	if !exists1 {
		t.Error("ctx1 should find its own entry")
	}

	// In Phase 5, this should also exist because they have same plan hash
	if !exists2 {
		t.Log("Note: ctx2 doesn't see ctx1's entry - this is expected if context fields affect key")
	}
}
